apiVersion: platform.platform.example.com/v1alpha1
kind: WebService
metadata:
  labels:
    app.kubernetes.io/name: pequod
    app.kubernetes.io/managed-by: kustomize
  name: webservice-sample
spec:
  # TODO(user): Add fields here
